name: EEAEConverter
version: 1.0
main: com.oneblockmc.converter.ConverterPlugin
author: Digital
api-version: 1.15
commands:
  dumpnbt:
    description: Dumps nbt on a item
    usage: /<command>
  fixenchants:
    description: Fixes enchants on tool
    usage: /<command>