package com.oneblockmc.converter;

import com.oneblockmc.converter.type.AEEnchant;
import com.oneblockmc.converter.type.EliteEnchant;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

public class EnchantRegistry {

    private final Map<EliteEnchant, AEEnchant> eliteToAeMap;
    public EnchantRegistry() {
        this.eliteToAeMap = new HashMap<>();
        init();
    }

    public Optional<AEEnchant> getEquivalent(EliteEnchant enchant) {
        return Optional.ofNullable(eliteToAeMap.get(enchant));
    }

    private void init() {
        eliteToAeMap.put(EliteEnchant.HEADLESS, AEEnchant.HEADLESS);
        eliteToAeMap.put(EliteEnchant.CONFUSION, AEEnchant.CONFUSION);
        eliteToAeMap.put(EliteEnchant.EXPERIENCE, AEEnchant.EXPERIENCE);
        eliteToAeMap.put(EliteEnchant.INSOMNIA, AEEnchant.INSOMNIA);
        eliteToAeMap.put(EliteEnchant.LIGHTNING, AEEnchant.LIGHTNING);
        eliteToAeMap.put(EliteEnchant.THUNDERING_BLOW, AEEnchant.THUNDERINGBLOW);
        eliteToAeMap.put(EliteEnchant.DECAPITATION, AEEnchant.DECAPITATION);
        eliteToAeMap.put(EliteEnchant.OBLITERATE, AEEnchant.OBLITERATE);
        eliteToAeMap.put(EliteEnchant.HASTE, AEEnchant.HASTE);
        eliteToAeMap.put(EliteEnchant.AUTO_SMELT, AEEnchant.AUTOSMELT);
        eliteToAeMap.put(EliteEnchant.AQUATIC, AEEnchant.AQUATIC);
        eliteToAeMap.put(EliteEnchant.GLOWING, AEEnchant.GLOWING);
        eliteToAeMap.put(EliteEnchant.OXYGENATE, AEEnchant.OXYGENATE);
        eliteToAeMap.put(EliteEnchant.FEATHERWEIGHT, AEEnchant.FEATHERWEIGHT);
        eliteToAeMap.put(EliteEnchant.NUTRITION, AEEnchant.SUSTAIN);
        eliteToAeMap.put(EliteEnchant.RAGDOLL, AEEnchant.RAGDOLL);
        eliteToAeMap.put(EliteEnchant.BERSERK, AEEnchant.BERSERK);
        eliteToAeMap.put(EliteEnchant.PLAGUE_CARRIER, AEEnchant.PLAGUECARRIER);
        eliteToAeMap.put(EliteEnchant.SELF_DESTRUCT, AEEnchant.SELFDESTRUCT);
        eliteToAeMap.put(EliteEnchant.EXPLOSIVE, AEEnchant.EXPLOSIVE);
        eliteToAeMap.put(EliteEnchant.MOLTEN, AEEnchant.MOLTEN);
        eliteToAeMap.put(EliteEnchant.RAVENOUS, AEEnchant.RAVENOUS);
        eliteToAeMap.put(EliteEnchant.ENDER_SHIFT, AEEnchant.ENDERSHIFT);
        eliteToAeMap.put(EliteEnchant.SKILL_SWIPE, AEEnchant.SKILLSWIPE);
        eliteToAeMap.put(EliteEnchant.VIRUS, AEEnchant.VIRUS);
        eliteToAeMap.put(EliteEnchant.CURSE, AEEnchant.CURSE);
        eliteToAeMap.put(EliteEnchant.TELEPATHY, AEEnchant.TELEPATHY);
        eliteToAeMap.put(EliteEnchant.GREATSWORD, AEEnchant.GREATSWORD);
        eliteToAeMap.put(EliteEnchant.HARDENED, AEEnchant.HARDENED);
        eliteToAeMap.put(EliteEnchant.PARALYZE, AEEnchant.PARALYZE);
        eliteToAeMap.put(EliteEnchant.ROCKET_ESCAPE, AEEnchant.ROCKETESCAPE);
        eliteToAeMap.put(EliteEnchant.BLIND, AEEnchant.BLIND);
        eliteToAeMap.put(EliteEnchant.ANTI_GRAVITY, AEEnchant.ANTIGRAVITY);
        eliteToAeMap.put(EliteEnchant.POISON, AEEnchant.POISON);
        eliteToAeMap.put(EliteEnchant.PUMMEL, AEEnchant.PUMMEL);
        eliteToAeMap.put(EliteEnchant.SHACKLE, AEEnchant.SHACKLE);
        eliteToAeMap.put(EliteEnchant.POISONED, AEEnchant.POISONED);
        eliteToAeMap.put(EliteEnchant.STORMCALLER, AEEnchant.STORMCALLER);
        eliteToAeMap.put(EliteEnchant.INFERNAL, AEEnchant.INFERNAL);
        eliteToAeMap.put(EliteEnchant.VENOM, AEEnchant.VENOM);
        eliteToAeMap.put(EliteEnchant.VAMPIRE, AEEnchant.VAMPIRE);
        eliteToAeMap.put(EliteEnchant.FROZEN, AEEnchant.FROZEN);
        eliteToAeMap.put(EliteEnchant.WITHER, AEEnchant.WITHER);
        eliteToAeMap.put(EliteEnchant.FARCAST, AEEnchant.FARCAST);
        eliteToAeMap.put(EliteEnchant.SNARE, AEEnchant.SNARE);
        eliteToAeMap.put(EliteEnchant.SHOCKWAVE, AEEnchant.SHOCKWAVE);
        eliteToAeMap.put(EliteEnchant.CACTUS, AEEnchant.CACTUS);
        eliteToAeMap.put(EliteEnchant.REFORGED, AEEnchant.REFORGED);
        eliteToAeMap.put(EliteEnchant.VOODOO, AEEnchant.VOODOO);
        eliteToAeMap.put(EliteEnchant.SPRINGS, AEEnchant.SPRINGS);
        eliteToAeMap.put(EliteEnchant.DEMONFORGED, AEEnchant.DEMONFORGED);
        eliteToAeMap.put(EliteEnchant.UNDEAD_RUSE, AEEnchant.UNDEADRUSE);
        eliteToAeMap.put(EliteEnchant.SMOKE_BOMB, AEEnchant.SMOKEBOMB);
        eliteToAeMap.put(EliteEnchant.EXECUTE, AEEnchant.EXECUTE);
        eliteToAeMap.put(EliteEnchant.TRICKSTER, AEEnchant.TRICKSTER);
        eliteToAeMap.put(EliteEnchant.TRAP, AEEnchant.TRAP);
        eliteToAeMap.put(EliteEnchant.MARKSMAN, AEEnchant.MARKSMAN);
        eliteToAeMap.put(EliteEnchant.BLOCK, AEEnchant.BLOCK);
        eliteToAeMap.put(EliteEnchant.DETONATE, AEEnchant.DETONATE);
        eliteToAeMap.put(EliteEnchant.ENDER_WALKER, AEEnchant.ENDERWALKER);
        eliteToAeMap.put(EliteEnchant.ICE_ASPECT, AEEnchant.ICEASPECT);
        eliteToAeMap.put(EliteEnchant.ASSASSIN, AEEnchant.ASSASSIN);
        eliteToAeMap.put(EliteEnchant.UNFOCUS, AEEnchant.UNFOCUS);
        eliteToAeMap.put(EliteEnchant.HEAVY, AEEnchant.HEAVY);
        eliteToAeMap.put(EliteEnchant.GUARDIANS, AEEnchant.GUARDIANS);
        eliteToAeMap.put(EliteEnchant.DODGE, AEEnchant.DODGE);
        eliteToAeMap.put(EliteEnchant.OBSIDIANSHIELD, AEEnchant.OBSIDIANSHIELD);
        eliteToAeMap.put(EliteEnchant.ARROW_LIFESTEAL, AEEnchant.ARROWLIFESTEAL);
        eliteToAeMap.put(EliteEnchant.HELLFIRE, AEEnchant.HELLFIRE);
        eliteToAeMap.put(EliteEnchant.VALOR, AEEnchant.VALOR);
        eliteToAeMap.put(EliteEnchant.ARROW_BREAK, AEEnchant.ARROWBREAK);
        eliteToAeMap.put(EliteEnchant.ENRAGE, AEEnchant.ENRAGE);
        eliteToAeMap.put(EliteEnchant.TANK, AEEnchant.TANK);
        eliteToAeMap.put(EliteEnchant.BLESSED, AEEnchant.BLESSED);
        eliteToAeMap.put(EliteEnchant.CLEAVE, AEEnchant.CLEAVE);
        eliteToAeMap.put(EliteEnchant.METAPHYSICAL, AEEnchant.METAPHYSICAL);
        eliteToAeMap.put(EliteEnchant.ARROW_DEFLECT, AEEnchant.ARROWDEFLECT);
        eliteToAeMap.put(EliteEnchant.PACIFY, AEEnchant.PACIFY);
        eliteToAeMap.put(EliteEnchant.DISINTEGRATE, AEEnchant.DISINTEGRATE);
        eliteToAeMap.put(EliteEnchant.SPIRITS, AEEnchant.SPIRITS);
        eliteToAeMap.put(EliteEnchant.IMPLANTS, AEEnchant.IMPLANTS);
        eliteToAeMap.put(EliteEnchant.DOMINATE, AEEnchant.DOMINATE);
        eliteToAeMap.put(EliteEnchant.LONGBOW, AEEnchant.LONGBOW);
        eliteToAeMap.put(EliteEnchant.ANGELIC, AEEnchant.ANGELIC);
        eliteToAeMap.put(EliteEnchant.PIERCING, AEEnchant.PIERCING);
        eliteToAeMap.put(EliteEnchant.EAGLE_EYE, AEEnchant.EAGLEEYE);
        eliteToAeMap.put(EliteEnchant.BLEED, AEEnchant.BLEED);
        eliteToAeMap.put(EliteEnchant.DEATH_GOD, AEEnchant.DEATHGOD);
        eliteToAeMap.put(EliteEnchant.HEX, AEEnchant.HEX);
        eliteToAeMap.put(EliteEnchant.BLACKSMITH, AEEnchant.BLACKSMITH);
        eliteToAeMap.put(EliteEnchant.DOUBLE_STRIKE, AEEnchant.DOUBLESTRIKE);
        eliteToAeMap.put(EliteEnchant.BARBARIAN, AEEnchant.BARBARIAN);
        eliteToAeMap.put(EliteEnchant.LIFESTEAL, AEEnchant.LIFESTEAL);
        eliteToAeMap.put(EliteEnchant.ENLIGHTED, AEEnchant.ENLIGHTED);
        eliteToAeMap.put(EliteEnchant.SILENCE, AEEnchant.SILENCE);
        eliteToAeMap.put(EliteEnchant.INVERSION, AEEnchant.INVERSION);
        eliteToAeMap.put(EliteEnchant.OVERLOAD, AEEnchant.OVERLOAD);
        eliteToAeMap.put(EliteEnchant.CLARITY, AEEnchant.CLARITY);
        eliteToAeMap.put(EliteEnchant.DEVOUR, AEEnchant.DEVOUR);
        eliteToAeMap.put(EliteEnchant.INQUISITIVE, AEEnchant.INQUISITIVE);
        eliteToAeMap.put(EliteEnchant.ARMORED, AEEnchant.ARMORED);
        eliteToAeMap.put(EliteEnchant.SNIPER, AEEnchant.SNIPER);
        eliteToAeMap.put(EliteEnchant.RAGE, AEEnchant.RAGE);
        eliteToAeMap.put(EliteEnchant.DRUNK, AEEnchant.DRUNK);
        eliteToAeMap.put(EliteEnchant.DEATH_BRINGER, AEEnchant.DEATHBRINGER);
        eliteToAeMap.put(EliteEnchant.DIMINISH, AEEnchant.DIMINISH);
        eliteToAeMap.put(EliteEnchant.GEARS, AEEnchant.GEARS);
        eliteToAeMap.put(EliteEnchant.INSANITY, AEEnchant.INSANITY);
        eliteToAeMap.put(EliteEnchant.DESTRUCTION, AEEnchant.DESTRUCTION);
        eliteToAeMap.put(EliteEnchant.EXTERMINATOR, AEEnchant.EXTERMINATOR);
        eliteToAeMap.put(EliteEnchant.TELEBLOCK, AEEnchant.TELEBLOCK);
        eliteToAeMap.put(EliteEnchant.IMMORTAL, AEEnchant.IMMORTAL);
        eliteToAeMap.put(EliteEnchant.DIVINE_IMMOLATION, AEEnchant.DIVINEIMMOLATION);
        eliteToAeMap.put(EliteEnchant.SABOTAGE, AEEnchant.SABOTAGE);
        eliteToAeMap.put(EliteEnchant.SOUL_TRAP, AEEnchant.SOULTRAP);
        eliteToAeMap.put(EliteEnchant.PHOENIX, AEEnchant.PHOENIX);
        eliteToAeMap.put(EliteEnchant.NATURE_WRATH, AEEnchant.NATURESWRATH);
        eliteToAeMap.put(EliteEnchant.GODLY_OVERLOAD, AEEnchant.GODLYOVERLOAD);
        eliteToAeMap.put(EliteEnchant.MASTER_INQUISITIVE, AEEnchant.MASTERINQUISITIVE);
        eliteToAeMap.put(EliteEnchant.SHADOW_ASSASSIN, AEEnchant.SHADOWASSASSIN);
        eliteToAeMap.put(EliteEnchant.ALIEN_IMPLANTS, AEEnchant.ALIENIMPLANTS);
        eliteToAeMap.put(EliteEnchant.ETHEREAL_DODGE, AEEnchant.ETHEREALDODGE);
        eliteToAeMap.put(EliteEnchant.PLANETARY_DEATHBRINGER, AEEnchant.PLANETARYDEATHBRINGER);
        eliteToAeMap.put(EliteEnchant.DIVINE_ENLIGHTED, AEEnchant.DIVINEENLIGHTED);
        eliteToAeMap.put(EliteEnchant.ATOMIC_DETONATE, AEEnchant.ATOMICDETONATE);
        eliteToAeMap.put(EliteEnchant.DEMONIC_LIFESTEAL, AEEnchant.DEMONICLIFESTEAL);
        eliteToAeMap.put(EliteEnchant.MASTER_BLACKSMITH, AEEnchant.MASTERBLACKSMITH);
        eliteToAeMap.put(EliteEnchant.PALADIN_ARMORED, AEEnchant.PALADINARMORED);
        eliteToAeMap.put(EliteEnchant.VENGEFUL_DIMINISH, AEEnchant.VENGEFULDIMINISH);
        eliteToAeMap.put(EliteEnchant.BIDIRECTIONAL_TELEPORTATION, AEEnchant.BIDIRECTIONALTELEPORTATION);
        eliteToAeMap.put(EliteEnchant.GUIDED_ROCKET_ESCAPE, AEEnchant.GUIDEDROCKETESCAPE);
        eliteToAeMap.put(EliteEnchant.MIGHTY_CACTUS, AEEnchant.MIGHTYCACTUS);
        eliteToAeMap.put(EliteEnchant.MIGHTY_CLEAVE, AEEnchant.MIGHTYCLEAVE);
        eliteToAeMap.put(EliteEnchant.POLYMORPHIC_METAPHYSICAL, AEEnchant.POLYMORPHICMETAPHYSICAL);
        eliteToAeMap.put(EliteEnchant.REFLECTIVE_BLOCK, AEEnchant.REFLECTIVEBLOCK);
        eliteToAeMap.put(EliteEnchant.REINFORCED_TANK, AEEnchant.REINFORCEDTANK);
        eliteToAeMap.put(EliteEnchant.TITAN_TRAP, AEEnchant.TITANTRAP);
        eliteToAeMap.put(EliteEnchant.BEWITCHED_HEX, AEEnchant.BEWITCHEDHEX);
        eliteToAeMap.put(EliteEnchant.EXTREME_INSANITY, AEEnchant.EXTREMEINSANITY);
        eliteToAeMap.put(EliteEnchant.MEGA_HEAVY, AEEnchant.MEGAHEAVY);
        eliteToAeMap.put(EliteEnchant.EPIDEMIC_CARRIER, AEEnchant.EPIDEMICCARRIER);
        eliteToAeMap.put(EliteEnchant.SOUL_HARDENED, AEEnchant.SOULHARDENED);
        // eliteToAeMap.put(EliteEnchant.NEUTRALIZE, ...);
        // eliteToAeMap.put(EliteEnchant.MORTAL_COIL, ...);
        // eliteToAeMap.put(EliteEnchant.DEEP_BLEED, ...);
        // eliteToAeMap.put(EliteEnchant.BLOOD_LUST, ...);
        // eliteToAeMap.put(EliteEnchant.BLOOD_LINK, ...);
        // eliteToAeMap.put(EliteEnchant.AEGIS, ...);
        // eliteToAeMap.put(EliteEnchant.ANTI_GANK, ...);
        // eliteToAeMap.put(EliteEnchant.FUSE, ...);
        // eliteToAeMap.put(EliteEnchant.LUCKY, ...);
        // eliteToAeMap.put(EliteEnchant.SOLITUDE, ...);
        // eliteToAeMap.put(EliteEnchant.OBSIDIAN_DESTROYER, ...);
        // eliteToAeMap.put(EliteEnchant.DEEP_WOUNDS, ...);
        // eliteToAeMap.put(EliteEnchant.HEALING, ...);
    }
}
